# config/manager/manager_patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          volumeMounts:
            - name: client-cert
              mountPath: /certs
              readOnly: true
            - name: ca-bundle
              mountPath: /ca
              readOnly: true
      volumes:
        - name: client-cert
          secret:
            secretName: kafka-client-cert
        - name: ca-bundle
          secret:
            secretName: kafka-ca-bundle