# permissions for end users to edit awsmskdemokafkaacls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-aws-msk-demo
    app.kubernetes.io/managed-by: kustomize
  name: awsmskdemokafkaacl-editor-role
rules:
- apiGroups:
  - aws.nttdata.com
  resources:
  - awsmskdemokafkaacls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.nttdata.com
  resources:
  - awsmskdemokafkaacls/status
  verbs:
  - get
