---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aws.nttdata.com
  resources:
  - awsmskdemokafkaacls
  - awsmskdemokafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.nttdata.com
  resources:
  - awsmskdemokafkaacls/finalizers
  - awsmskdemokafkatopics/finalizers
  verbs:
  - update
- apiGroups:
  - aws.nttdata.com
  resources:
  - awsmskdemokafkaacls/status
  - awsmskdemokafkatopics/status
  verbs:
  - get
  - patch
  - update
