apiVersion: aws.nttdata.com/v1alpha1
kind: AwsMSKDemoKafkaTopic
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-aws-msk-demo
    app.kubernetes.io/managed-by: kustomize
  name: awsmskdemokafkatopic37-demo
spec:
  clusterArn: arn:aws:kafka:eu-central-1:063010046250:cluster/aboczek-msk-cluster-manu1/8b0b2493-fc95-4660-a91d-d4cc12eb162e-8
  name: "awsmskdemooperator-topic37"
  partitions: 1
  replicationFactor: 3
  acls:
    - principal: "User:CN="         # operator expects tls brokers, so the principal is the CN from client certificate
      permissionType: "Allow"
      operation: "Describe"
    - principal: "User:CN="
      permissionType: "Allow"
      operation: "Read"
    - principal: "User:CN="
      permissionType: "Allow"
      operation: "Write"
    - principal: "User:CN="
      permissionType: "Allow"
      operation: "Delete"