//go:build !ignore_autogenerated

/*
Copyright 2025 NTT DATA.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsMSKDemoKafkaACL) DeepCopyInto(out *AwsMSKDemoKafkaACL) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsMSKDemoKafkaACL.
func (in *AwsMSKDemoKafkaACL) DeepCopy() *AwsMSKDemoKafkaACL {
	if in == nil {
		return nil
	}
	out := new(AwsMSKDemoKafkaACL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsMSKDemoKafkaTopic) DeepCopyInto(out *AwsMSKDemoKafkaTopic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsMSKDemoKafkaTopic.
func (in *AwsMSKDemoKafkaTopic) DeepCopy() *AwsMSKDemoKafkaTopic {
	if in == nil {
		return nil
	}
	out := new(AwsMSKDemoKafkaTopic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AwsMSKDemoKafkaTopic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsMSKDemoKafkaTopicList) DeepCopyInto(out *AwsMSKDemoKafkaTopicList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AwsMSKDemoKafkaTopic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsMSKDemoKafkaTopicList.
func (in *AwsMSKDemoKafkaTopicList) DeepCopy() *AwsMSKDemoKafkaTopicList {
	if in == nil {
		return nil
	}
	out := new(AwsMSKDemoKafkaTopicList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AwsMSKDemoKafkaTopicList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsMSKDemoKafkaTopicSpec) DeepCopyInto(out *AwsMSKDemoKafkaTopicSpec) {
	*out = *in
	if in.ACLs != nil {
		in, out := &in.ACLs, &out.ACLs
		*out = make([]AwsMSKDemoKafkaACL, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsMSKDemoKafkaTopicSpec.
func (in *AwsMSKDemoKafkaTopicSpec) DeepCopy() *AwsMSKDemoKafkaTopicSpec {
	if in == nil {
		return nil
	}
	out := new(AwsMSKDemoKafkaTopicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsMSKDemoKafkaTopicStatus) DeepCopyInto(out *AwsMSKDemoKafkaTopicStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsMSKDemoKafkaTopicStatus.
func (in *AwsMSKDemoKafkaTopicStatus) DeepCopy() *AwsMSKDemoKafkaTopicStatus {
	if in == nil {
		return nil
	}
	out := new(AwsMSKDemoKafkaTopicStatus)
	in.DeepCopyInto(out)
	return out
}
